Updated packs
panther-labs/panther-analysis pull request #1038
Opened 2023-12-13 14:54 UTC by melenevskyi

### Background

Updated packs

2023-12-13 15:01 UTC, egibs submitted a review, later dismissed

2023-12-13 15:44 UTC, arielkr256 commented on packs/atlassian.yml
> +    - Confluence.0DayIPs
These IOCs were last updated # 2022-06-02 Confluence 0-Day IOCs: This rule probably needs to be deprecated.

2023-12-13 15:46 UTC, arielkr256 commented on packs/onepassword.yml
> +    - OnePassword.Login.From.CrowdStrike.Unmanaged.Device
I like how rules that require multiple log sources are in both packs

2023-12-13 15:49 UTC, arielkr256 commented on packs/panther.yml
> +    - IOC.SunburstFQDNIOCs
All of these IOC/0DayIP rules need to be deprecated, they are pretty stale at this point.  Also the IOC.Log4jExploit rule I believe causes severe performance issues.

2023-12-13 15:49 UTC, arielkr256 requested changes
Deprecate IOC rules and remove from packs

2023-12-15 10:18 UTC, le4ker approved these changes

2024-01-16 16:50 UTC, merged