kbailey: potentially malicious SSO DNS lookup
panther-labs/panther-analysis pull request #490
Opened 2022-09-10 02:13 UTC by k-bailey

### Background

Recently there was an active and successful phishing campaign targeting major tech companies using fake SSO/VPN login pages for credential harvesting. This detection attempts to look for the domain name patterns these attackers used in DNS requests.

ref: https://blog.group-ib.com/0ktapus

### Changes

* New rule & config

### Testing

* Make lint/test/fmt
* Data replay using "Panther" as the configured company

2022-09-10 02:35 UTC, edyesed requested changes
I'm interpreting this detection as behaving in a way to fast-exit if p_any_domain_names has anything from the allow list in it. I  suspect this needs to be restructured to return True if  any malicious domain is found vs returning False if any good domain is found.

2022-09-10 02:41 UTC, edyesed commented on rules/standard_rules/malicious_sso_dns_lookup.py
> +    # filter out known good domains
something like this, I think 

```python
for domain in event.get("p.any_domain_names", []):
   domain_was_allowed = [x for x in ALLOWED_DOMAINS if domain.lower().endswith(x)]
   if domain_was_allowed:
      continue # loop to next domain in p_any_domain_names
   if COMPANY_NAME in domain.lower():
      fake_matches = [ x for x in FAKE_KEYWORDS if x in domain.lower() ]
      if fake_matches:
          return True
     return False

```

2022-09-10 02:48 UTC, edyesed commented on rules/standard_rules/malicious_sso_dns_lookup.yml
> +
We should have a test case where p_any_domain_names has both good and bad domains in it, with the good domain first in the list.

2022-09-10 22:05 UTC, jpl5280 commented on rules/standard_rules/malicious_sso_dns_lookup.py
> +you own, that conain your company name, false positive alerts will be generated.
`conain` -> `contain`

2022-09-12 17:09 UTC, k-bailey commented on rules/standard_rules/malicious_sso_dns_lookup.py
> +    # filter out known good domains
fixed, discussed in person

2022-09-12 17:17 UTC, edyesed approved these changes
this new detection will look for potentially malicious SSO DNS lookups as in the recent oktapus campaign

2022-09-12 17:30 UTC, merged