fix: customer reported that sometimes box_parse_additional_details could raise an error when trying to json.loads
panther-labs/panther-analysis pull request #516
Opened 2022-09-26 23:18 UTC by edyesed

### Background

sometimes `event['additional_details']` is typed to not-a-string when processing box events. `json.loads()` wanted a string-ish input. 

### Changes

* This change catches the TypeError being raised by json.loads in `panther_base_helpers.box_parse_additional_details` and provides a feature-equivalent alternative result set, if the TypeError is for one of the panther ImmutableXXX types.

### Testing

* I added a new unit test file and make target to run unit tests in `global_helpers/*_test.py` ( note: it only works as long as there's a single file matching the pattern ). 

ATTN: @panther-labs/detections for extra 👀

2022-09-27 15:33 UTC, calkim-panther approved these changes

2022-09-29 14:37 UTC, darwayne requested changes
based on @lindsey-w's latest internal feedback we should move away from introducing panther-core as a dependency

2022-09-29 16:57 UTC, edyesed commented
@darwayne  + @lindsey-w  , I believe this is what the internal discussion said we should do

2022-09-29 17:05 UTC, darwayne reviewed
This looks right to me, would like to get additional verification from @lindsey-w

2022-09-29 17:22 UTC, lindsey-w approved these changes
Thanks Ed!

2022-09-29 17:23 UTC, lindsey-w commented on Makefile
> +	pipenv run python global_helpers/*_test.py
++

2022-09-29 17:25 UTC, merged