Added 2 new AWS Odin Detections
panther-labs/panther-analysis pull request #525
Opened 2022-10-06 17:46 UTC by hbenac10

Background
MITRE T1525 CloudTrail Detections

[MITRE IaaS Gap] - T1578 - Modify Cloud Compute Infrastructure
[MITRE IaaS Gap] - T1498 - regular detection - WAF disassociate

Changes
New detections

2022-10-06 19:27 UTC, darwayne commented on rules/aws_cloudtrail_rules/aws_modify_cloud_compute_infrastructure.yml
> +    - 'MITRE ATT&CK: T1578'
You'll want this to match [this format](https://github.com/panther-labs/panther-analysis/blob/cd220c87982011d4ad156c7daecd2857c358d154/rules/osquery_rules/osquery_linux_logins_non_office.yml#L13-L15) for this to show in the MITRE Matrix

```suggestion
Reports:
  MITRE ATT&CK:
    - TA0005:T1578
```

2022-10-06 19:28 UTC, darwayne commented on rules/aws_cloudtrail_rules/aws_waf_disassociation.yml
> +    - 'MITRE ATT&CK: TA0004:T1078'
You'll want this to match [this format](https://github.com/panther-labs/panther-analysis/blob/cd220c87982011d4ad156c7daecd2857c358d154/rules/osquery_rules/osquery_linux_logins_non_office.yml#L13-L15) for this to show in the MITRE Matrix

```suggestion
Reports:
  MITRE ATT&CK:
    - TA0004:T1078
```

2022-10-12 17:09 UTC, edyesed requested changes
IMO, we should separate out the aws_modify_cloud_compute detection from this PR. As currently written, the modify_compute detection will fire for every ec2:TerminateInstance command that happens in the cloudtrail, which will lead to alert fatigue in ec2 rich environments.

2022-10-14 20:01 UTC, edyesed commented
replaced by #532

2022-10-14 20:01 UTC, closed without merging