TA0007:T1046
panther-labs/panther-analysis pull request #536
Opened 2022-10-20 15:10 UTC by calkim-panther

### Background

TA0007:T1046: Network Service Discovery
This detection is looking for port scanning activity. 
The other example on MITRE is looking for all ListServices, but that api seems to be used everywhere. 

### Testing

* ci

2022-10-20 18:33 UTC, darwayne approved these changes

2022-10-25 23:36 UTC, edyesed commented on rules/aws_vpc_flow_rules/aws_port_enumeration.py
> +    if (
```suggestion
    if  not all([
        event.get("srcaddr"),
        event.get("dstaddr"),
        event.get("srcport"),
        event.get("dstport")
    ]):
```

2022-10-25 23:36 UTC, edyesed commented on rules/aws_vpc_flow_rules/aws_port_enumeration.py
> +            accessed_ports = ast.literal_eval(accessed_ports)
I would be substantially more comfortable if we used `json.loads()` plus typecasting to a `set()` instead of `literal_eval()`.

2022-10-25 23:39 UTC, edyesed requested changes
I like this detection a great deal, and I would like to find an alternate to the `literal_eval()`

2022-11-28 17:26 UTC, closed without merging