New Rule: Duo Admin Lockout
panther-labs/panther-analysis pull request #609
Opened 2022-12-19 21:21 UTC by andrea-youwakim

### Background

<High level overview here>

### Changes

* newly written duo rule to alert on admin lockout

### Testing

* 
<img width="1362" alt="Screen Shot 2022-12-19 at 3 18 59 PM" src="https://user-images.githubusercontent.com/117778222/208526247-1aed5ff3-c7e7-43ef-b559-db4c23891bc0.png">

2022-12-19 21:34 UTC, jpl5280 commented on rules/duo_rules/duo_admin_lockout.py
> +        f"Duo User [{event.get('username', '<NO_USER_FOUND>')}] is "
```suggestion
        f"Duo Admin [{event.get('username', '<NO_USER_FOUND>')}] is "
```

2022-12-19 21:48 UTC, jpl5280 commented on rules/duo_rules/duo_admin_lockout.py
> +        f"temporarily locked out due to too many passcode attempts."
I'm not sure the description is static (aka `Admin temporarily locked out due to too many passcode attempts.` may only be 1 of many reasons'). Suggestion: 

pseudocode"

`f"locked out. Reason: event.get('description').get('message')"`

2022-12-19 21:49 UTC, jpl5280 commented on rules/duo_rules/duo_admin_lockout.yml
> +    - Duo.Authentication
i dont think we need this one, in this case?

2022-12-20 21:44 UTC, jpl5280 commented on rules/duo_rules/duo_admin_lockout.py
> +        f"Duo User [{event.get('username', '<NO_USER_FOUND>')}] is "
```suggestion
        f"Duo Admin [{event.get('username', '<NO_USER_FOUND>')}] is "
```

2022-12-20 21:53 UTC, jpl5280 approved these changes

2022-12-21 17:16 UTC, edyesed requested changes

2022-12-21 17:16 UTC, edyesed commented on rules/duo_rules/duo_admin_lockout.py
> +        f"[{event.get('description', {}).get('message','<NO_MESSAGE_FOUND>')}]."
I expect that this is aways returning `<NO_MESSAGE_FOUND>` from the test suite. `event.description` is a string which needs to be `json.loads()`'ed to understand that there is a `message` attribute in there.

2022-12-21 18:43 UTC, edyesed approved these changes
duo detection for admin lockout

2022-12-21 18:43 UTC, merged