AWS discovery Rules
panther-labs/panther-analysis pull request #621
Opened 2023-01-10 16:39 UTC by hbenac10

### Background

Created odin aws discovery rule

2023-01-10 18:29 UTC, andrea-youwakim commented
lint and test failing

2023-01-10 21:06 UTC, calkim-panther requested changes

2023-01-10 21:06 UTC, calkim-panther commented on rules/aws_cloudtrail_rules/aws_software_discovery.yml
> +Severity: High
Should be an Info level imo.

2023-01-18 20:00 UTC, calkim-panther approved these changes

2023-01-25 16:19 UTC, merged