Calkim duo detections
panther-labs/panther-analysis pull request #637
Opened 2023-01-17 17:12 UTC by calkim-panther

### Background

<High level overview here>

### Changes

* <Describe changes here>

### Testing

* <Testing steps>

2023-01-17 17:21 UTC, jpl5280 commented
@calkim-panther - can you put the output from CLI testing in the PR description? Helps to see the dynamically generated titles, etc

2023-01-17 20:59 UTC, jpl5280 requested changes

2023-01-17 20:59 UTC, jpl5280 commented on rules/duo_rules/duo_admin_user_mfa_bypass_enabled.py
> +        " to not require two-factor authentication."
extra space

2023-01-17 20:59 UTC, jpl5280 commented on rules/duo_rules/duo_admin_user_mfa_bypass_enabled.py
> +        " to not require two-factor authentication."
```suggestion
        "to not require two-factor authentication."
```

2023-01-17 20:59 UTC, jpl5280 commented on rules/duo_rules/duo_admin_create_admin.py
> +        "created a new admin account for "
```suggestion
        "created a new admin account: "
```

2023-01-20 19:40 UTC, andrea-youwakim approved these changes

2023-01-20 19:54 UTC, jpl5280 approved these changes

2023-01-20 19:55 UTC, merged