Aws mitre t1606
panther-labs/panther-analysis pull request #646
Opened 2023-01-20 20:47 UTC by hbenac10

### Background

Adding aws mitre t1606 to Odin detections.

2023-01-24 00:29 UTC, edyesed requested changes

2023-01-24 00:29 UTC, edyesed commented on rules/aws_cloudtrail_rules/aws_software_discovery.py
> +        f"User [{deep_get(event, 'userIdentity', 'principalId')}] "
please use `userIdentity.arn`

2023-01-24 00:29 UTC, edyesed commented on rules/aws_cloudtrail_rules/aws_software_discovery.py
> +        f"performed a [{event.get('eventName')}] "
I know we haven't historically included the Threshold in the title, and I'm wondering if it makes sense to say that the actor has already done `N` number of these items.

2023-01-24 00:29 UTC, edyesed commented on rules/aws_cloudtrail_rules/aws_software_discovery.yml
> +        - T1518:T1518.001
my understanding is that the web UI doesn't handle subtechniques. 
I think this will need to be `TAxxxx:Txxxx`

2023-01-24 00:29 UTC, edyesed commented on rules/aws_cloudtrail_rules/aws_s3_applogs_collection.yml
> +        - T1213
This needs to be format `TAxxxx:Txxxx`

2023-01-24 00:29 UTC, edyesed commented on rules/aws_cloudtrail_rules/aws_reconnaissance_collection.yml
> +        - TA0009
`TAxxxx:Txxxx`

2023-01-25 15:38 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_authentication_improbable_access.py
> +from datetime import datetime, timedelta
Nate and I had this conversation and think we should have an anomalous helper.

2023-01-25 15:56 UTC, natezpanther commented on rules/aws_cloudtrail_rules/aws_authentication_improbable_access.py
> +from datetime import datetime, timedelta
Hey @edyesed I totally agree. I would like to update our global helpers to include:

- DynamoDB - `put_dictionary()` and `get_dictionary()`, that would handle serializing and de-serializing dictionaries and putting/getting them from DynamoDB. These would alleviate the string set-to-dict conversions that are implemented in several detections that use DynamoDB stateful caching
- Distance calculation with Lat/Long values - `haversine_distance()`

Would that be something I could work up in its own PR?

2023-01-27 00:59 UTC, edyesed commented on rules/aws_cloudtrail_rules/aws_authentication_improbable_access.py
> +from datetime import datetime, timedelta
absolutely something that you can work up into its own PR 👍 

Also agree that the distance calculation belongs out in the helpers. This is a valuable technique we can apply to lots of different logtypes 💯

2023-02-16 15:50 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_authentication_improbable_access.py
> +from datetime import datetime, timedelta
Just notating this as completed.

2023-02-16 15:50 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_authentication_improbable_access.py
> +AUTH_EVENTS = [
Fixed.

2023-02-16 15:51 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_authentication_improbable_access.yml
> +Description: Monitor for creation of access tokens
Fixed.

2023-02-16 15:51 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_authentication_improbable_access.py
> +        f"User [{deep_get(event, 'userIdentity', 'principalId')}] "
Fixed.

2023-02-16 16:13 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_reconnaissance_collection.yml
> +        - TA0009
Fixed.

2023-02-17 15:22 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_reconnaissance_collection.py
> +    if event.get("eventSource") != "s3.amazonaws.com":
Fixed.

2023-02-17 15:42 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_reconnaissance_collection.yml
> +Description: The adversary is trying to gather data of interest to their goal.
Fixed.

2023-02-17 15:42 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_reconnaissance_collection.py
> +    )
Fixed.

2023-02-17 15:42 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_reconnaissance_collection.py
> +    return True
Fixed.

2023-02-17 15:43 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_reconnaissance_collection.py
> +events = {
Fixed.

2023-02-17 15:43 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_reconnaissance_collection.py
> +    if event.get("errorCode"):
Fixed.

2023-02-17 17:01 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_s3_applogs_collection.py
> +# Deduplicaton and threshold events may vary on environment, adjust as needed.
Now that we have detection filters in place, is it necessary to do this into the code.  Now users can add any filters needed.

2023-02-17 17:27 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_s3_applogs_collection.py
> +# Deduplicaton and threshold events may vary on environment, adjust as needed.
Fixed.

2023-02-17 17:28 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_s3_applogs_collection.py
> +
Fixed

2023-02-17 17:28 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_s3_applogs_collection.py
> +        f"User ({deep_get(event, 'userIdentity', 'sessionContext', 'sessionIssuer', 'userName')})  "
Fixed.

2023-02-17 17:28 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_s3_applogs_collection.py
> +    return (
Fixed.

2023-02-17 17:28 UTC, hbenac10 commented on rules/aws_cloudtrail_rules/aws_s3_applogs_collection.yml
> +        - T1213
Fixed.

2024-10-22 15:21 UTC, closed without merging