Tines Rules 2x - Job Deletion
panther-labs/panther-analysis pull request #787
Opened 2023-06-13 16:15 UTC by josh-panther

### Background

https://www.tines.com/api/audit-logs#:~:text=JobsQueuedDeletion,retrying%20jobs%20were%20cleared%20(for%20a%20self%2Dhosted%20tenant)

Tines - JobsQueuedDeletion, JobsRetryingDeletion
Created via Panther Console and exported to PAT.
Default severity low but I have no strong opinion about that.
Also, the runbook/etc are blank - open to suggestions for those fields.

### Changes

* 2 rules

### Testing

Unable to test in actual tines, as requires "self-hosted" tines instance

![image](https://github.com/panther-labs/panther-analysis/assets/101294262/2f65870c-c12e-47ed-8962-e9ecafca3e23)

2023-06-13 16:33 UTC, edyesed requested changes
Please add an `ExpectedResult: false` test case and set the alert_context using the [tines global helper alert_context](https://github.com/panther-labs/panther-analysis/blob/master/global_helpers/panther_tines_helpers.py#L1)

2023-06-13 16:33 UTC, edyesed commented on rules/tines_rules/tines.enqueued_retrying.job.deletion.py
> +    tines_instance = event.get('p_source_label')
please use `deep_get()` with a `default=` kwarg  in place of `event.get()`

2023-06-13 16:33 UTC, edyesed commented on rules/tines_rules/tines.enqueued_retrying.job.deletion.py
> +    return f"Tines {operation} by {user} on {tines_instance}"
```suggestion
    return f"Tines [{operation}] by [{user}] on [{tines_instance}]"
```

2023-06-14 15:56 UTC, josh-panther commented
Waiting for https://github.com/panther-labs/panther-analysis/pull/786 before review req

2023-06-26 21:38 UTC, edyesed approved these changes
adds detection for tines operations that relate to data destruction

2023-06-26 22:00 UTC, merged