Tines Story Items Destruction rule
panther-labs/panther-analysis pull request #788
Opened 2023-06-13 16:37 UTC by josh-panther

### Background

https://www.tines.com/api/audit-logs#:~:text=resource%20was%20created-,ResourceDestruction,-A%20global%20resource

Tines - Global Resource Destruction. Defaults, created via Panther Console and exported to PAT.
Default severity low but I have no strong opinion about that.
Also, the runbook/etc are blank - open to suggestions for those fields.

### Changes

* Tines - Global Resource Destruction rule

### Testing

![image](https://github.com/panther-labs/panther-analysis/assets/101294262/b1e0a684-cb3c-4cd7-a8e5-c29c67829e02)

Validated on Panther Version: 1.70.22
<Pending API collecting data>

2023-06-13 17:38 UTC, andrea-youwakim commented
failing lint and test

2023-06-13 18:17 UTC, edyesed requested changes

2023-06-13 18:17 UTC, edyesed commented on rules/tines_rules/tines_story_items_destruction.py
> +    return event.get('operation_name') == 'StoryItemsDestruction'
please use `deep_get()` with a `default=` kwarg in place of `event.get()`

2023-06-13 18:17 UTC, edyesed commented on rules/tines_rules/tines_story_items_destruction.py
> +    return f"Tines {operation} by {user} on {tines_instance}"
Variable interpolation should use square brackets around the interpolation. please convert these to also use `deep_get`
```suggestion
    return f"Tines [{operation}] by [{user}] on [{tines_instance}]"
```

2023-06-13 18:17 UTC, edyesed commented on rules/tines_rules/tines_story_items_destruction.py
> +    return f"Tines {operation} by {user} on {tines_instance}"
This detection should use the global helper for tines to provide alert_context https://github.com/panther-labs/panther-analysis/blob/master/global_helpers/panther_tines_helpers.py#L1

2023-06-13 18:17 UTC, edyesed commented on rules/tines_rules/tines_story_items_destruction.py
> +    return event.get('operation_name') == 'StoryItemsDestruction'
The Tines.Audit log type has a global filter, this should be the first thing that happens inside the rule function https://github.com/panther-labs/panther-analysis/blob/master/rules/tines_rules/tines_custom_ca.py#L11-L12

2023-06-13 18:17 UTC, edyesed commented on rules/tines_rules/tines_story_items_destruction.yml
> +Tests:
We need a test case that has `ExpectedResult: false` to demonstrate that this does not alert on every log event passed into it.

2023-06-14 15:59 UTC, josh-panther commented
Waiting for https://github.com/panther-labs/panther-analysis/pull/786 before review req

2023-06-15 12:52 UTC, josh-panther commented
I made this info level severity per https://www.notion.so/Hackathon-Tines-StoryActions-Destruction-a7a2da9e783e47e1aab1ceea9d3fef6f?d=ee9596cd6dfc4bfdaea23f1b8130cf7d&pvs=4

If someone wants to override me on that feel free but I don't feel super comfortable with it even at "Low" - Given my understanding of how Tines workflows typically go. If I'm wrong just let me know 👍

2023-06-26 22:07 UTC, edyesed approved these changes
adds a Info level detection for Tines story items destruction. While this is a data-destruction classified event, it is also a somewhat common event in Tines stories as workflows are modified.

2023-06-26 22:07 UTC, merged