add: notion rule scim token generated
panther-labs/panther-analysis pull request #796
Opened 2023-06-13 22:42 UTC by LucySuddenly

### Background

<High level overview here>

### Changes

* <Describe changes here>

### Testing

* <Testing steps>

2023-06-14 17:38 UTC, calkim-panther approved these changes

2023-06-14 18:44 UTC, andrea-youwakim requested changes

2023-06-15 16:49 UTC, andrea-youwakim requested changes
one super minor change requested, otherwise this looks great to me

do you mind also updating the output in the pr description once this change is in? just for ease of visibility and understanding of desired functionality when people take a look at this pr :) 

otherwise great work here !! thanks for your participation ~

2023-06-15 17:48 UTC, andrea-youwakim approved these changes

2023-06-15 17:49 UTC, merged