Add helpers to convert to hashable and parse akin to deep_walk
panther-labs/panther-analysis pull request #843
Opened 2023-06-29 21:19 UTC by egibs

### Background

This PR uses #819 as inspiration and adds a way to convert an object to an object that is 100% hashable along with a way to parse the new object like `deep_walk` would with dictionaries/lists.

The reasoning for this is that `deep_walk` can potentially return an `ImmutableList` which can cause issues if further parsing is required on the returned value(s).

### Changes

* Adds `to_hashable` helper function
* Adds `deep_walk_hashable` helper function
* Adds tests for both helper functions
* Updates the `gcp_access_attempts_violating_vpc_service_controls.py` detection to use the `deep_walk_hashable` and `to_hashable` helpers as an example

### Testing

* New tests pass as expected

2023-06-29 21:35 UTC, edyesed requested changes
I don't quite understand why this is needed. the unit test framework should get the inputs set to PantherEvent which subclass immutabledict/immutablelist as needed. 

I would like to see a test case for gcp_access_attempts_violation that demonstrates the conditions leading to this.

2023-06-29 22:00 UTC, egibs commented
@edyesed -- yea, I could have been more clear -- here's what I was running into with `gcp_access_attempts_violating_vpc_service_controls.py` and `deep_walk`:
```
GCP.Access.Attempts.Violating.VPC.Service.Controls
        [PASS] Other Event
                [PASS] [rule] false
        [FAIL] VPC control violation
                [FAIL] [rule] TypeError: unhashable type: 'ImmutableList'
                [PASS] [title] GCP: [user1@serviceaccount.gcp.com] performed a [google.storage.objects.get] request that violates VPC Service Controls
                [PASS] [dedup] GCP: [user1@serviceaccount.gcp.com] performed a [google.storage.objects.get] request that violates VPC Service Controls
```

Using:
```py
def rule(event):
    if event.get("severity", "") == "ERROR":
        if deep_get(event, "protoPayload", "status", "code") == 7:
            for violation in deep_walk(event, "protoPayload", "status", "details", "violations", default=""):
                if violation == "VPC_SERVICE_CONTROLS":
                    return True
    return False
```
or
```py
def rule(event):
    if event.get("severity", "") == "ERROR":
        if deep_get(event, "protoPayload", "status", "code") == 7:
            return "VPC_SERVICE_CONTROLS" in deep_walk(event, "protoPayload", "status", "details", "violations", default="")
    return False
```


I can work on some test cases that exhibit this as well.

2023-06-29 22:05 UTC, edyesed commented
> @edyesed -- yea, I could have been more clear -- here's what I was running into with `gcp_access_attempts_violating_vpc_service_controls.py` and `deep_walk`:
> 
> ```
> GCP.Access.Attempts.Violating.VPC.Service.Controls
>         [PASS] Other Event
>                 [PASS] [rule] false
>         [FAIL] VPC control violation
>                 [FAIL] [rule] TypeError: unhashable type: 'ImmutableList'
>                 [PASS] [title] GCP: [user1@serviceaccount.gcp.com] performed a [google.storage.objects.get] request that violates VPC Service Controls
>                 [PASS] [dedup] GCP: [user1@serviceaccount.gcp.com] performed a [google.storage.objects.get] request that violates VPC Service Controls
> ```
> 
> Using:
> 
> ```python
> def rule(event):
>     if event.get("severity", "") == "ERROR":
>         if deep_get(event, "protoPayload", "status", "code") == 7:
>             for violation in deep_walk(event, "protoPayload", "status", "details", "violations", default=""):
>                 if violation == "VPC_SERVICE_CONTROLS":
>                     return True
>     return False
> ```
> 
> or
> 
> ```python
> def rule(event):
>     if event.get("severity", "") == "ERROR":
>         if deep_get(event, "protoPayload", "status", "code") == 7:
>             return "VPC_SERVICE_CONTROLS" in deep_walk(event, "protoPayload", "status", "details", "violations", default="")
>     return False
> ```
> 
> I can work on some test cases that exhibit this as well.

I am under the impression that it is intended behavior for lists to be unhashable 😅

2023-06-30 17:53 UTC, egibs commented
Going to close this out but we can re-open if the need arises. It was a fun thought exercise at any rate!

2023-06-30 17:53 UTC, closed without merging